global using Siftly.IntegrationTest.Entities;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.Extensions.DependencyInjection;
global using Siftly.IntegrationTest.Data;
global using Xunit;
global using Siftly.IntegrationTest.Fixtures;
global using FluentAssertions;
global using Siftly.Core;
global using Siftly.EntityFramework;